lane :test do
  make(file: '/Users/xiongzenghui/Desktop/amake')

  make(
    file: '/Users/xiongzenghui/Desktop/amake',
    target: 'all'
  )

  make(
    file: '/Users/xiongzenghui/Desktop/amake',
    target: 'all',
    envs: {NAME: 'xiongzenghui', AGE: 99}
  )

  make(
    file: '/Users/xiongzenghui/Desktop/amake',
    target: 'all',
    envs: {NAME: 'xiongzenghui', AGE: 99},
    jobs: '2'
  )
end